// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
insert into orders (quantity, shipping_address, sku, idempotency_key) values ($1, $2, $3, $4) returning id, quantity, created_at, updated_at, status, idempotency_key, shipping_address, sku
`

type CreateOrderParams struct {
	Quantity        int32
	ShippingAddress string
	Sku             pgtype.UUID
	IdempotencyKey  pgtype.UUID
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Quantity,
		arg.ShippingAddress,
		arg.Sku,
		arg.IdempotencyKey,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.ShippingAddress,
		&i.Sku,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
select id, quantity, created_at, updated_at, status, idempotency_key, shipping_address, sku from orders
where id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.ShippingAddress,
		&i.Sku,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
select id, quantity, created_at, updated_at, status, idempotency_key, shipping_address, sku from orders
where idempotency_key = $1
`

func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, idempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.ShippingAddress,
		&i.Sku,
	)
	return i, err
}
